name: Nasa Project CI
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use NodeJS version 12.22
        uses: actions/setup-node@v3
        with:
          node-version: '12.22'
      - run: npm install
      - run: npm install --prefix client
      - run: npm install --prefix server
      - run: BUILD_PATH=../server/public npm run build --prefix client
