name: Nasa Project CI
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
jobs:
  build:
    env:
      CI: true
    strategy:
      matrix:
        mongodb-version: ['4.4']
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use NodeJS version 12.22
        uses: actions/setup-node@v3
        with:
          node-version: '12.22'
      - name: Set up Mongo for Testing
        uses: supercharge/mongodb-github-action@1.7.0
        with:
          mongodb-version: ${{matrix.mongodb-version}}
      - run: npm install
      - run: BUILD_PATH=../server/public npm run build --prefix client
      - run: npm run test
